version: "3"
services:    
    postgres:        
        image: postgres:15        
        environment:            
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres        
        volumes:            
            - ./dados:/var/lib/postgresql/data                    
        ports:            
            - 6542:5432